name: Docs Build Check 

on:
  pull_request:
    branches: [main]

jobs:
  build-check:
    name: Test Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Test build website
        run: bun run build
